Feature/add metadb tests
mskcc/beagle pull request #995
Opened 2022-02-01 22:10 UTC by nikhil

- There is an issue when handling samples names, beagle expects a `s_` prefix, but the metadb fixture did not include one on cmoSampleName
- The metadb_import branch is not in a mergable state:
   - Some of the tests in lims_etl are failing from previous commits
   - There are many merge conflicts with develop

2022-02-01 22:11 UTC, nikhil commented
All the tests contributed in this PR are passing:

```
╰─ python3 manage.py test beagle_etl.tests.jobs.test_metadb                                                               ─╯
Creating test database for alias 'default'...
No file group or file_types defined
421287a5-e138-45e7-afd6-5d860e60aa6c
Could not pull remote statuses
System check identified no issues (0 silenced).
......
----------------------------------------------------------------------
Ran 6 tests in 0.416s

OK
Destroying test database for alias 'default'...
```

2022-02-01 22:28 UTC, nikhil commented
We should also document this function and modifications we do to the data after importing from metadb: https://github.com/mskcc/beagle/blob/feature/add_metadb_tests/beagle_etl/jobs/metadb_jobs.py#L714

Especially since we are overloading the sampleName field with cmoSampleName.

2022-02-01 23:59 UTC, allanbolipata requested changes
You bring up `cmoSampleName` - we actually should talk about this before we proceed any further

2022-02-04 15:28 UTC, sivkovic approved these changes

2022-02-04 16:31 UTC, merged